services:
  valetax.app:
    image: valetax.app
    build:
      context: .
      dockerfile: Valetax.App/Dockerfile
    restart: unless-stopped
    expose:
      - "5046"
      - "7177"
    ports:
      - "5046:80"
      - "7177:7177"
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -N 1000
    environment:
      - POSTGRES_DB=valetax
      - POSTGRES_PASSWORD=admin
    expose:
      - "5432"
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - data-valetax:/var/lib/postgresql/data
volumes:
  data-valetax: